blank_issues_enabled: false
contact_links:
  - name: Discord des contributeurs
    url: https://discord.com/invite/fkkCXsBrmE
    about: Espace de collaboration rassemblant tous les bénévoles qui participent activement à la maintenance du site internet Discord FR
