name: Suggestion de modification
description: Suggérez un article à modifier sur le Wiki Discord FR
title: "[Suggestion]: Modification de l'article 'TITRE'"
labels: ["modification"]
body:
  - type: input
    id: title
    attributes:
      label: Titre de l'article
      description: Quel est le titre de l'article que vous souhaitez modifier sur le Wiki ?
      placeholder: ex. Abonnements Nitro
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Problématique
      description: Qu'est-ce cet article devrait contenir comme nouvelle information·s ?
      placeholder: |
        ex. Nouvel abonnement :

        - Nitro Basic

        Ancien abonnement supprimé :

        - Nitro Classic
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Informations supplémentaires
      description: Il y a-t-il des information additionnelles que vous souhaitez ajouter à l'Issue ? (ex. liens vers documentation, images, etc.)
      placeholder: |
        ex. Avantages de chaque abonnement : https://discord.com/nitro
    validations:
      required: false
  - type: checkboxes
    id: validation
    attributes:
      label: Avant de valider
      options:
        - label: J'ai bien vérifié que l'article existe, ne contient pas déjà l'information, et que la modification n'a pas déjà été suggérée
          required: true
        - label: J'ai bien lu et accepté les règles de contribution du Wiki
          required: true
        - label: Je souhaite participer à la rédaction de l'article si ma suggestion est acceptée
          required: false
